"use strict";let menubtn=document.querySelector(".menu");let cancelbtn=document.querySelector(".cancel-container");let menubar=document.querySelector(".menu-bar");menubtn.addEventListener("click",()=>{menubar.style.transform="translateX(0)";document.body.style.overflow="hidden"});cancelbtn.addEventListener("click",()=>{menubar.style.transform="translateX(-100%)";document.body.style.overflow="auto"});const sliderContent={"vintage-and-antique":{title:"Vintage & Antique",price:"4500",discount:"Take 20% off for a limited time.",code:"LOVE20",},"hidden-halo":{title:"Hidden Halo",price:"3500",discount:"Take 10% off for a limited time.",code:"LOVE10",},pave:{title:"Pave",price:"2500",discount:"Take 5% off for a limited time.",code:"LOVE05",},};function initSlider(){const slider=document.querySelector(".slider");const slides=Array.from(slider.querySelectorAll("img"));const positions=["left","center","right"];let isAnimating=!1;setInitialPositions();addClickListeners();startAutoPlay();updateContent();function setInitialPositions(){slides.forEach((slide,index)=>{slide.setAttribute("data-position",positions[index])})}
function addClickListeners(){slides.forEach((slide)=>{slide.addEventListener("click",()=>{if(!isAnimating&&slide.dataset.position!=="center"){moveSlides(slide)}})})}
function updateSlideSize(slide){if(slide.dataset.position==="center"){const customWidth=slide.dataset.customWidth;const customHeight=slide.dataset.customHeight;slide.style.setProperty("--active-width",`${customWidth}px`);slide.style.setProperty("--active-height",`${customHeight}px`)}}
function moveSlides(clickedSlide){if(isAnimating)return;isAnimating=!0;removeFadeClasses();const currentPositions=slides.map((slide)=>slide.dataset.position);const clickedPosition=clickedSlide.dataset.position;setTimeout(()=>{slides.forEach((slide,index)=>{updateSlideSize(slide);const currentPos=currentPositions[index];slide.dataset.position=getNextPosition(currentPos,clickedPosition==="left"?"left":"right")});updateContent();setTimeout(()=>{isAnimating=!1},900)},50)}
function getNextPosition(currentPos,direction){const positionMap={left:{left:"center",center:"right",right:"left"},right:{left:"right",center:"left",right:"center"},};return positionMap[direction][currentPos]}
function updateContent(){const centerSlide=slides.find((slide)=>slide.dataset.position==="center");const slideId=centerSlide.src.split("/").pop().split(".")[0];const content=sliderContent[slideId];setTimeout(()=>{document.querySelector(".hero-product-title").textContent=content.title;document.querySelector(".main-text").textContent=content.title;document.querySelector(".product-price span").textContent=content.price;const productInfo=document.querySelector(".product-info");productInfo.children[0].textContent=content.discount;productInfo.children[1].textContent=`Use Code: ${content.code}`;addFadeClasses()},450)}
function removeFadeClasses(){const elements=document.querySelectorAll(".main-container > *");elements.forEach((el)=>el.classList.remove("fade-up"))}
function addFadeClasses(){const elements=document.querySelectorAll(".main-container > *");elements.forEach((el,index)=>{setTimeout(()=>{el.classList.add("fade-up")},index*100)})}
function startAutoPlay(){setInterval(()=>{if(!isAnimating){const rightSlide=slides.find((slide)=>slide.dataset.position==="right");moveSlides(rightSlide)}},5000)}}
document.addEventListener("DOMContentLoaded",initSlider);let activeIndex=3;let isAnimatings=!1;const cards=document.querySelectorAll(".diamond-card");const dots=document.querySelectorAll(".dot");function getInitialIndex(){const screenWidth=window.innerWidth;if(screenWidth<=480){return 1}else if(screenWidth<=768){return 2}
return 3}
function updateDotsVisibility(){const screenWidth=window.innerWidth;dots.forEach((dot,index)=>{if(screenWidth<=480){dot.style.display=index<3?"block":"none"}else if(screenWidth<=768){dot.style.display=index<5?"block":"none"}else{dot.style.display="block"}})}
function rotateSlides(targetIndex){if(isAnimatings)return;isAnimatings=!0;const totalCards=cards.length;const positions=Array.from(cards).map((_,index)=>{let newPosition=index-targetIndex;if(newPosition<-3)newPosition+=totalCards;if(newPosition>3)newPosition-=totalCards;return newPosition});const screenWidth=window.innerWidth;cards.forEach((card,index)=>{card.setAttribute("data-position",positions[index]);if(screenWidth<=480){card.style.display=positions[index]>=-1&&positions[index]<=1?"block":"none"}else if(screenWidth<=768){card.style.display=positions[index]>=-2&&positions[index]<=2?"block":"none"}else{card.style.display="block"}});dots.forEach((dot,index)=>{if(dot.style.display!=="none"){dot.classList.toggle("active",index===targetIndex)}});setTimeout(()=>{activeIndex=targetIndex;isAnimatings=!1},800)}
document.addEventListener("DOMContentLoaded",()=>{cards.forEach((card,index)=>{card.addEventListener("click",()=>rotateSlides(index))});dots.forEach((dot,index)=>{dot.addEventListener("click",()=>rotateSlides(index))});updateDotsVisibility();activeIndex=getInitialIndex();rotateSlides(activeIndex);window.addEventListener("resize",()=>{updateDotsVisibility();activeIndex=getInitialIndex();rotateSlides(activeIndex)})})